pandorabox-io/pandorabox.io

docker-compose.yml
Changes:
* https://github.com/pandorabox-io/minetest_docker/commit/1baba9de74fc242cada71538d5b0f7e01c806673
=> switch engine to 5.3.0-r4

config/metatool.cfg, docker-compose.yml
Related: https://github.com/pandorabox-io/pandorabox-mods/pull/1099
**NOTE:** this _will_ restart the minetest-server due to changed path-configs
=> add metatool config and wire it into the container

docker-compose.yml
fixes the path to the metatool config
=> fix metatool config path

docker-compose.yml
=> add and enable mapcleaner

minetest.conf
[if this PR](https://github.com/minetest-beerchat/beerchat/pull/24) is accepted, then this one here is needed to enable the new feature.
=> set moderator channel

config/beerchat.js, docker-compose.yml
requires https://github.com/minetest-beerchat/beerchat_proxy/pull/56 to work
=> add public beerchat config

minetest.conf
It does not hurt to merge, but I'm still waiting on upstream to decide on my PR about ccompass_nodes_over_target_allow
=> ccompass settings adjustments

minetest.conf
Prerequisite for https://github.com/pandorabox-io/pandorabox-mods/pull/1289
=> add default hotbar size of 8 slots

minetest.conf
These wont do anything anymore after https://github.com/mt-mods/technic/pull/111
To actually apply these new config file should be created for technic.
=> Remove deprecated technic configuration

docker-compose.yml
Reverts pandorabox-io/pandorabox.io#625
too much map sending/saving overhead
=> Revert "switch to minetest 5.4.0-r3"

minetest.conf
=> Enable beerchat announce extension

minetest.conf
Requires some testing but in this case probably fine to test in production and revert if it does not seem to work as expected.
=> SAO send range from 2 to 3

config/beerchat.js
fixes #656
(i have no idea if the unicode thing works)
=> add "💡ideas" channel to ingame

minetest.conf
https://github.com/pandorabox-io/in-game/issues/54
=> Set stamina.tick_min to 1

config/beerchat.js
I created #reports in-game, wasn't sure what color to use so made it pink, as a reference to the admin armor.
Resolves https://github.com/pandorabox-io/in-game/issues/109
=> Link #reports channel to in-game

minetest.conf
https://github.com/pandorabox-io/pandorabox-mods/pull/2206
=> Set headlamp battery life to 60 minutes

docker-compose.yml
=> switch to `buckaroobanzay/minetest:5.5.0-r4`

docker-compose.yml
See: https://github.com/pandorabox-io/pandorabox.io/issues/733
=> auto-updater for the skins repo

minetest.conf
* `/channel-alias <Alias name> [<Channel Name>]`
* `/channel-unalias <Alias name>`
=> Enable Beerchat alias extension

docker-compose.yml
Reverts pandorabox-io/pandorabox.io#789
=> Revert "Update ghcr.io/minetest-go/mtui Docker tag to v1.38"

.gitmodules, docker-compose.yml, renovate.json
=> engine `5.8.0` and minetest_game as submodule

docker-compose.yml
Test instance for this running at `test.pandorabox.io` with the state of 2025-03-09 02:00 UTC
Including the following mod PR's:
* https://github.com/pandorabox-io/pandorabox-mods/pull/4062
=> luanti `5.11.0`

docker-compose.yml
https://www.postgresql.org/docs/current/runtime-config-wal.html#RUNTIME-CONFIG-WAL-SETTINGS
(live at test.pandorabox.io, tests pending)
=> pg optimizations
